[package]
name = "clt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
rand = "0.8.5"
plotters = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.8"